//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int id { get; set; }
        public string numberCard { get; set; }
        public System.DateTime endDate { get; set; }
        public int cardInfoId { get; set; }
        public int contractId { get; set; }
    
        public virtual CardInfo CardInfo { get; set; }
        public virtual ContractClient ContractClient { get; set; }
    }
}
