//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int id { get; set; }
        public int clientId { get; set; }
        public int creditInfoId { get; set; }
        public int creditTime { get; set; }
        public System.DateTime dateCredit { get; set; }
        public int transactionId { get; set; }
        public int amountCredit { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual CreditInfo CreditInfo { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
