//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int id { get; set; }
        public int depositInfoId { get; set; }
        public System.DateTime startDateDeposit { get; set; }
        public System.DateTime endDateDeposit { get; set; }
        public int clientId { get; set; }
        public int transactionId { get; set; }
        public int amountDeposit { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DepositInfo DepositInfo { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
