//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int id { get; set; }
        public System.DateTime datePayments { get; set; }
        public int clientId { get; set; }
        public int transactionId { get; set; }
        public int paymentsInfoId { get; set; }
        public int amountPayments { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PaymentsInfo PaymentsInfo { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
